### ISSUE TITLE
point loss in mask loss

### ISSUE THREAD

**Issue by liuqk3** [IDEA-Research/MaskDINO#13]
Hi @FengLi-ust , thanks for your great works!

In  the appendix, you stated that `We also follow [17, 5, 4] to use point loss in mask loss for efficiency`. There are some details that I can not figured out:
1) How to sample the points?  with (a) regular grid, (b) uniform, (c) mildly biased or (d) heavily biased? How many points are smpled for each query?
2) The dot product in eq (1) will introduce losts of computation and memory cost. Did you sample the point features from `M(T(C_b)+F(C_e))` for each query before performing the dot production? While sampling, which kind of boxes are used, GT boxes or anchor boxes?
3) Is there an obvious APm gap between the point (mask) loss and the mask loss without sampling?

**Comment by FengLi-ust** [comment]
Hi, you can refer to our cited papers for more details about how to sample and its gain.
