### ISSUE TITLE
MaskDINO 12 epoch results with 100 queries

### ISSUE THREAD

**Issue by KimHanjung** [IDEA-Research/MaskDINO#16]
Hi, @FengLi-ust. I'm very interested in your great work!

When I read your paper, it's method still works well in 100 queries setting. So did you evaluate your method with 1x a schedule on COCO?

Thank you again for your elaborate work and I look forward to hearing from you.

**Comment by FengLi-ust** [comment]
Hi, we show the performance of using 100 queries for 50 epochs in our paper. Do you mean you want to know the performance of using 100 queries for 12 epochs?

**Comment by KimHanjung** [comment]
Yes, that't right. I want to know the performance of using 100 queries for 12 epochs setting.

**Comment by KimHanjung** [comment]
I see. Thank you for your reply.

**Comment by KimHanjung** [comment]
I will keep that in mind. Thank you again for your kind reply.
