### ISSUE TITLE
Models cannot train with negative examples

### ISSUE THREAD

**Issue by KaiKaneshina** [IDEA-Research/MaskDINO#20]
I was trying to train using images with no annotations by setting the filter empty annotations flag to false. However the code crashes out in the coco parsing and later down the line when gt_masks is referenced.  When using negative examples, the instance object won’t have gt_masks.

**Comment by FengLi-ust** [comment]
Can you give more details about your problem?

**Comment by KaiKaneshina** [comment]
In line 178 in coco_instance_new_baseline_dataset_mapper.py, the instances object is assumed to have a gt_masks field. However, if the original image has no annotations, this field will not exist. 
`instances.gt_boxes = instances.gt_masks.get_bounding_boxes()`

I think this check needs to go inside of the `if hasattr(instances, 'gt_masks'):` on line 184

**Comment by KaiKaneshina** [comment]
The aforementioned fix is not sufficient, as the `prepare_targets` and `prepare_targets_detr` both create dictionaries assuming that the gt_masks field is present in the instances object.

**Comment by FengLi-ust** [comment]
Yes, and we may also need to modify the loss calculation part. 

I think another simpler way is to filter the images without annotations. It is useless to pass these images to Mask DINO.

**Comment by KaiKaneshina** [comment]
Are negative examples not supposed to effect the loss function in mask DINO? Or are they not currently supported?

**Comment by FengLi-ust** [comment]
Yes, I do not think it will. Unless this negative image actually does not contain any objects and the model is trained to predict no object in this image. But I think you also need to add an annotation for this case, for example, the box annotation is an empty list [].

Actually, COCO also contains these kinds of images that have empty box annotations.

**Comment by KaiKaneshina** [comment]
Yes, the negative images have no annotations and the model should predict that no objects are present. I was under the impression that for negative images the coco json just has the image but not a corresponding annotation [as shown here.](https://blog.roboflow.com/missing-and-null-image-annotations/amp/)

**Comment by FengLi-ust** [comment]
When I load these images without any objects, I get annotations with GT boxes as an empty list. I am not sure if COCO annotates these images or if the preprocessing part does this job. 

You can take a look at this code to solve your problem.

**Comment by KaiKaneshina** [comment]
Training with negative images works with the following code changes to `coco_instance_new_baseline_dataset_mapper.py`. We just need to add an empty 'gt_masks' field to the instance object, before the call on line 178:
  ```
if not instances.has('gt_masks'): 
     instances.gt_masks = PolygonMasks([])
instances.gt_boxes = instances.gt_masks.get_bounding_boxes()
```
The PolygonMasks structure can be imported from detectron2.structures.

**Comment by KaiKaneshina** [comment]
Will the files in the above PR be updated in this repo?

**Comment by FengLi-ust** [comment]
Yes, I update it with yours. Thanks.

> Training with negative images works with the following code changes to `coco_instance_new_baseline_dataset_mapper.py`. We just need to add an empty 'gt_masks' field to the instance object, before the call on line 178:
> 
> ```
> if not instances.has('gt_masks'): 
>    instances.gt_masks = PolygonMasks([])
> instances.gt_boxes = instances.gt_masks.get_bounding_boxes()
> ```
> 
> The PolygonMasks structure can be imported from detectron2.structures.

**Comment by KaiKaneshina** [comment]
Thanks!
