### ISSUE TITLE
Can this model be trained from instance segmentation COCO format?

### ISSUE THREAD

**Issue by Robotatron** [IDEA-Research/MaskDINO#25]
OneFormer requires custom dataset to be in a panoptic COCO format which differs from things detection COCO format.
Can this model be trained from instance segmentation COCO format? Or will I have to convert  things detection COCO format to panoptic?

**Comment by FengLi-ust** [comment]
Yes, Mask DINO can.

**Comment by Robotatron** [comment]
Thank you Feng
