### ISSUE TITLE
Inference demo with pre-trained MaskDINO model 

### ISSUE THREAD

**Issue by MeAmarP** [IDEA-Research/MaskDINO#27]
Hello Team,
Thanks for publishing code. I was impressed by results that you have published in paper. Compared to other top leaderboard ( on https://paperswithcode.com/sota/instance-segmentation-on-coco )  models for instance segmentation problem. MaskDINO is using quit a low # of parameters and yet acheiving better score. Hence, In my current application we are planning to use MaskDINO and was trying to do some infer tests.

- I was able to setup a env as per installation requirment shared in repo.

I just wanted to know if you could also add demo infer, just like detectron2 has in its getting started section.
https://detectron2.readthedocs.io/en/latest/tutorials/getting_started.html

Or else let me know how I can modify detectron2 demo.py script so I can run it.

**Comment by ShijieVVu** [comment]
I think you can just use Mask2Former's demo folder for this purpose.

**Comment by FengLi-ust** [comment]
Thanks for this comment. We will add a demo infer.

**Comment by MeAmarP** [comment]
Thanks @ShijieVVu That worked for me, 

btw why you guys have not renamed method at https://github.com/IDEA-Research/MaskDINO/blob/main/maskdino/config.py as 
`add_maskdino_config()`.

Also let me know shall I PR to add demo for MaskDINO.

**Comment by MeAmarP** [comment]
Thanks

**Comment by FengLi-ust** [comment]
You can PR and add a demo for Mask DINO. Thanks.
