### ISSUE TITLE
How to do inference on single gpu, getting cuda oom error.

### ISSUE THREAD

**Issue by rsingh-aiborne** [IDEA-Research/MaskDINO#30]
When trying to inference one image using detectron2 default predictor, I am getting cuda oom error on a single 15 gb T4 gpu. Any help?

**Comment by FengLi-ust** [comment]
Mask DINO can be inference with 1 GPU. If you are not using our predictor, maybe you are setting the batch size too large? You can try setting inference batch size 1.
