### ISSUE TITLE
To filter output results by confidence score

### ISSUE THREAD

**Issue by MeAmarP** [IDEA-Research/MaskDINO#36]
Hi Team,

Am trying to create demo for MaskDINO, refer https://github.com/MeAmarP/MaskDINO/tree/quickfix/infer_demo

If am correct currently maskdino gives 100 infers per frame. which sometimes overally populates per detected object with overlayed info when visualising using demo.py.

It would be great if we can filter by using cli arg config-score. But am unable to trace where in code we can perform filtering for predictions.

Need little help/guidence here.

**Comment by FengLi-ust** [comment]
You can try setting a classification threshold of 0.3.

**Comment by MeAmarP** [comment]
Hey @FengLi-ust Thanks.. I found this from detectron2 docs that can help. I will try.

**Comment by saprrow** [comment]
(https://github.com/IDEA-Research/MaskDINO/blob/ba96e4aaa156db15b2858c562aafaf28aac2c2ec/maskdino/maskdino.py#L468)
Maybe you can change this line to ` keep[i] = lab in self.metadata.thing_dataset_id_to_contiguous_id.values() and scores_per_image[i] > 0.5` and `0.5` is the confidence threshold

**Comment by sunlight002** [comment]
How did you finally solve this problem?
