### ISSUE TITLE
RuntimeError: Global alloc not supported yet

### ISSUE THREAD

**Issue by KaiKaneshina** [IDEA-Research/MaskDINO#48]
I tried running mask dino recently with the latest code and a new environment. I run into a `RuntimeError: Global alloc not supported yet`  using the batch_dice_loss_jit function on line 166 in matcher.py.
This error appears to go away if I just switch to using the regular batch_dice_loss instead. 
My new environment is using pytorch 1.10, detectron2 0.6, and cuda 11.2.

I saw that in your detrex repository, you have already adjusted the code to no longer use jit.
https://github.com/IDEA-Research/detrex/issues/161

Is the detrex repository replacing/being updated more often than this repository? Should I switch to using that one instead?

**Comment by FengLi-ust** [comment]
Well, you can use both repos, and this repo has more results and codes. I forgot to fix this bug you mentioned, and I will fix it immediately.
