### ISSUE TITLE
Mask/box denoising hparams

### ISSUE THREAD

**Issue by vadimkantorov** [IDEA-Research/MaskDINO#5]
What noise hyper-params are used in MaskDINO? Thanks!

Is there any noise added to "init anchors"?

what is "Unified denoising for mask" / "Unified DN" in figure 1? any special losses for this?

Does MaskDINO also use deformable attention? Both in encoder and in decoder?

**Comment by liuqk3** [comment]
Hi @FengLi-ust ,
Thanks for your wonderful works. In  the paper, Section 3.2, third paragraph, “It does not support mask refinement as the mask positional prediction from one layer cannot pass to the next layer.” Dose this mean that the masks are also refined layer-by-layer like boxes in MaskDINO? If it does, how to add masks that predicted by previous layer to current layer?
