### ISSUE TITLE
ade20k semantic segmentation doesn't run

### ISSUE THREAD

**Issue by KaiKaneshina** [IDEA-Research/MaskDINO#55]
I tried running the ade20k semantic segmentation today, but it failed to run
`python train_net.py --config-file maskdino_R50_bs16_160k_steplr.yaml`

I had to comment out the `BASE_LR_END` kwarg in the solver, as this key doesn't exist.

Once I fixed that, I ran into this issue:
`
  File "MaskDINO/maskdino/data/dataset_mappers/mask_former_semantic_dataset_mapper.py", line 181, in __call__
    instances.gt_boxes = masks.get_bounding_boxes()
AttributeError: 'list' object has no attribute 'get_bounding_boxes'
`

**Comment by KaiKaneshina** [comment]
This seems to fix the issue.
![image](https://user-images.githubusercontent.com/32587279/221331467-0bd1b5a9-bfc5-444a-9df6-f9e0d3958dc2.png)

**Comment by FengLi-ust** [comment]
Thanks. You can create a pull request if possible.

**Comment by KaiKaneshina** [comment]
#56
