### ISSUE TITLE
About inference speed

### ISSUE THREAD

**Issue by Wilbur529** [IDEA-Research/MaskDINO#60]
Hi, thanks for your brilliant work! 
Now i am trying the experiment with 'R50/300queries' setting. The model converges well and works well, but the inference speed **(>120ms/f, ≈8.3fps)** is significantly lower than which reported in the paper **(14.2fps, ≈70ms/f)**. It's worth noting that I also used A100 GPU, and i only counted the time spent on model processing (including post-processing, but not image I/O).
Could you please share the inference speed test script or some debugging tips? @FengLi-ust

**Comment by FengLi-ust** [comment]
Following the common practice, we only consider computing time. Post-processing is to handle COCO evaluation, so it is not included.

**Comment by Wilbur529** [comment]
The inference speed i tested on A100 is >120ms/f, ≈8.3fps, and i also didn't conside coco-eval part. But i added the box&mask post-processing part. Do you have plan to release relevant speed test scripts in the future?

**Comment by FengLi-ust** [comment]
Hi, there is no script for testing speed. Whenever you do the coco inference, the detectron2 logger will output the compute time `inference pure compute time` and total time `Total inference time`. This is an example of one previous model logging:
<img width="1123" alt="image" src="https://user-images.githubusercontent.com/34880758/227406971-0d5f5a62-0dbe-4a89-85c8-603161006201.png">

**Comment by Wilbur529** [comment]
Thx! I got a similar result with you.
<img width="1414" alt="image" src="https://user-images.githubusercontent.com/30430969/227437648-12a6d774-e6a9-42f7-8ba3-98c3b87ae09d.png">
