### ISSUE TITLE
Inference on CPU.

### ISSUE THREAD

**Issue by fedllanes** [IDEA-Research/MaskDINO#67]
I'm trying to do inference on CPU, however even though i set the device to CPU and even the tensors, i still get this error.

Any idea why? Has anyone been successful? 

---------------------------------------------------------------------------
RuntimeError                              Traceback (most recent call last)
/tmp/ipykernel_605/4001456572.py in <module>
     13         image = torch.as_tensor(image.astype("float32").transpose(2, 0, 1)).to(device)
     14         inputs = {"image": image, "height": height, "width": width}
---> 15         predictions = _model([inputs])[0]
     16 end = time.time()

/usr/local/lib/python3.7/dist-packages/torch/nn/modules/module.py in _call_impl(self, *input, **kwargs)
   1100         if not (self._backward_hooks or self._forward_hooks or self._forward_pre_hooks or _global_backward_hooks
   1101                 or _global_forward_hooks or _global_forward_pre_hooks):
-> 1102             return forward_call(*input, **kwargs)
   1103         # Do not call functions when jit is used
   1104         full_backward_hooks, non_full_backward_hooks = [], []

/data/maskdino/jupyter/MaskDINO/maskdino/maskdino.py in forward(self, batched_inputs)
    275             return losses
    276         else:
--> 277             outputs, _ = self.sem_seg_head(features)
    278             mask_cls_results = outputs["pred_logits"]
    279             mask_pred_results = outputs["pred_masks"]

/usr/local/lib/python3.7/dist-packages/torch/nn/modules/module.py in _call_impl(self, *input, **kwargs)
   1100         if not (self._backward_hooks or self._forward_hooks or self._forward_pre_hooks or _global_backward_hooks
   1101                 or _global_forward_hooks or _global_forward_pre_hooks):
-> 1102             return forward_call(*input, **kwargs)
   1103         # Do not call functions when jit is used
   1104         full_backward_hooks, non_full_backward_hooks = [], []

/data/maskdino/jupyter/MaskDINO/maskdino/modeling/meta_arch/maskdino_head.py in forward(self, features, mask, targets)
     73 
     74     def forward(self, features, mask=None,targets=None):
---> 75         return self.layers(features, mask,targets=targets)
     76 
     77     def layers(self, features, mask=None,targets=None):

/data/maskdino/jupyter/MaskDINO/maskdino/modeling/meta_arch/maskdino_head.py in layers(self, features, mask, targets)
     78         mask_features, transformer_encoder_features, multi_scale_features = self.pixel_decoder.forward_features(features, mask)
     79 
---> 80         predictions = self.predictor(multi_scale_features, mask_features, mask, targets=targets)
     81 
     82         return predictions

/usr/local/lib/python3.7/dist-packages/torch/nn/modules/module.py in _call_impl(self, *input, **kwargs)
   1100         if not (self._backward_hooks or self._forward_hooks or self._forward_pre_hooks or _global_backward_hooks
   1101                 or _global_forward_hooks or _global_forward_pre_hooks):
-> 1102             return forward_call(*input, **kwargs)
   1103         # Do not call functions when jit is used
   1104         full_backward_hooks, non_full_backward_hooks = [], []

/data/maskdino/jupyter/MaskDINO/maskdino/modeling/transformer_decoder/maskdino_decoder.py in forward(self, x, mask_features, masks, targets)
    464             spatial_shapes=spatial_shapes,
    465             valid_ratios=valid_ratios,
--> 466             tgt_mask=tgt_mask
    467         )
    468         for i, output in enumerate(hs):

/usr/local/lib/python3.7/dist-packages/torch/nn/modules/module.py in _call_impl(self, *input, **kwargs)
   1100         if not (self._backward_hooks or self._forward_hooks or self._forward_pre_hooks or _global_backward_hooks
   1101                 or _global_forward_hooks or _global_forward_pre_hooks):
-> 1102             return forward_call(*input, **kwargs)
   1103         # Do not call functions when jit is used
   1104         full_backward_hooks, non_full_backward_hooks = [], []

/data/maskdino/jupyter/MaskDINO/maskdino/modeling/transformer_decoder/dino_decoder.py in forward(self, tgt, memory, tgt_mask, memory_mask, tgt_key_padding_mask, memory_key_padding_mask, pos, refpoints_unsigmoid, level_start_index, spatial_shapes, valid_ratios)
    125 
    126             reference_points_input = reference_points[:, :, None] \
--> 127                                          * torch.cat([valid_ratios, valid_ratios], -1)[None, :]  # nq, bs, nlevel, 4
    128             query_sine_embed = gen_sineembed_for_position(reference_points_input[:, :, 0, :]) # nq, bs, 256*2
    129 

RuntimeError: Expected all tensors to be on the same device, but found at least two devices, cuda:0 and cpu!

**Comment by FengLi-ust** [comment]
Thanks for your contribution! Issue closed.
