### ISSUE TITLE
parallel demo gets some wrong results

### ISSUE THREAD

**Issue by huxycn** [IDEA-Research/MaskDINO#68]
modify "demo/demo.py" to use parallel prediction

![image](https://user-images.githubusercontent.com/49256066/230434829-71a5e5e0-dc6d-4b55-8696-66fa251c40ce.png)

run this command:
`python demo/demo.py --config-file configs/ade20k/semantic-segmentation/maskdino_R50_bs16_160k_steplr.yaml --input ../demo_imgs --output ../demo_imgs_output/ --opts MODEL.WEIGHTS ../maskdino_r50_50ep_100q_celoss_hid1024_3s_semantic_ade20k_48.7miou.pth`

demo_imgs directory 
![image](https://user-images.githubusercontent.com/49256066/230435229-e83fa040-f9f2-4ebb-b056-1b84295afda1.png)

demo_imgs_output directory
![image](https://user-images.githubusercontent.com/49256066/230435638-940da379-65e4-4dd5-a6dd-46443f4007bb.png)

some results mask values are all zeros, which indicates to "wall" class
![image](https://user-images.githubusercontent.com/49256066/230436320-cb9c2d60-d976-470d-8e0c-34fff67b995f.png)

**Comment by FengLi-ust** [comment]
Sorry for the late reply. Thanks for your comments! If you find out the solution to this problem, you are encouraged to raise a PR to contribute to this repo. Thanks!

**Comment by huxycn** [comment]
it's not MultiScaleDeformableAttention bug, but the AsyncPredictor bug, try this gist: https://gist.github.com/priyathamkat/31d6b931095358840ba4bf073127864c
