### ISSUE TITLE
masks of instance segmentation

### ISSUE THREAD

**Issue by fschvart** [IDEA-Research/MaskDINO#7]
Hi,

I trained a model with a custom dataset, the bbox seems pretty solid. I was wondering how can I get the instance mask? I looked at the inference notebook and looked at the output of the model and I'm not sure what I"m missing, but I couldn't find any mask parameters.

My goal is eventually to do instance/panoptic segmentation. 

Thanks!

**Comment by FengLi-ust** [comment]
Which codebase did you use?

**Comment by fschvart** [comment]
The DINO one, from my understanding, it doesn't support instance segmentation

**Comment by FengLi-ust** [comment]
Yes, DINO cannot do segmentation. Mask DINO is another paper to make DINO achieve good performance in segmentation tasks with three proposed methods. Please refer to our paper for more details.
