### ISSUE TITLE
Table 2, model params clarification

### ISSUE THREAD

**Issue by oxpie** [IDEA-Research/MaskDINO#8]
Hi!

Table 2 shows Mask DINO's total parameter count as below. Cloud you please check if the numbers are correct? Specially for Mask DINO with 24 epochs. It looks like there was a typo and the number was carried from Mask2Former.

| Model | Epochs | Query type | Params |
|-|-|-|-|
Mask2Former | 50 | 100 queries | 44M |
| Mask DINO (ours) | 50 | 100 queries | 50M |
| Mask DINO (ours) | 50 | 300 queries | 50M |
| Mask DINO (ours) | 24 | 300 queries | 44M |
Mask2Former | 12 | 100 queries | 44M |
| Mask DINO (ours) | 12 | 300 queries | 50M |

Thank you!

**Comment by FengLi-ust** [comment]
Thanks for your careful reading. It is a typo. We will update this number to `50M` in our next version.

**Comment by oxpie** [comment]
Sorry for reopening this issue, but I just figured out that by simply changing `dec_layers` to `9` gives 51.3M params for the R50 DINO model. And that is before adding the mask head. Maybe I am missing something but, apart from the learnable content queries, was there any other thing that you were able to remove from the model in order to get to 50M params?

Thank you!

**Comment by oxpie** [comment]
Thanks for the answer, but I still don't understand it completely.

DINO already has sharing turned on by default (the paper even mentions that doing it saves 1M params). I am sorry if I am missing something, but I don't think that the Mask DINO text mentions changes in the detection head. Could you please elaborate further?

Thank you!
