### ISSUE TITLE
Share the reproduce results

### ISSUE THREAD

**Issue by hrfng** [IDEA-Research/MaskDINO#84]
Thanks for the wonderful work.

```
mask-dino swim-L 50ep： box map 58.2, seg mask 51.9 (repo 59.0, 52.3) 8 x a100
Notice: stopped in the intermediate for the disk full problem,  restart with --resume flag a.g.
 
Mask-dino resnet 50ep, 4xa100
box map：51.375 seg mask 46.23 (repo, box map 51.7 seg map 46.3) 
```

Users what to use the algorithm, may escape the reproduce phrase.

**Comment by xianghong2023** [comment]
Hello, I would like to ask what configuration file was used to reproduce the results under resnet50, and have any modifications been made? The results I reproduced here are significantly different from those in the paper report. I would like to know where the problem occurred? I really hope to receive your reply.
