### ISSUE TITLE
What config need to be changed for change in input image size.

### ISSUE THREAD

**Issue by rgkannan676** [IDEA-Research/MaskDINO#85]
Hi,

Thank you for this repo.

I have a doubt @FengLi-ust , For training larger images for instance segmentation, which config should I change? I don't want the preprocessing step to resize the image to a smaller dimension.  For example, my input image size is 3000 x 2500, which config should I change?

I saw the following configs in "configs/coco/instance-segmentation/Base-COCO-InstanceSegmentation.yaml", is this where I should change?

INPUT:
  IMAGE_SIZE: 1024
  MIN_SCALE: 0.1
  MAX_SCALE: 2.0

Can you please advise what the value for image size 3000 x 2500. 

Thanks,
Kannan

**Comment by rgkannan676** [comment]
https://github.com/IDEA-Research/MaskDINO/blob/3435d14c04f926eed87c14455be6dbd412d7bbed/maskdino/data/dataset_mappers/coco_panoptic_new_baseline_dataset_mapper.py#L21
https://github.com/facebookresearch/detectron2/blob/eddac5d5b4fce9b5eba5518f9ee348fa3a531407/detectron2/data/transforms/augmentation_impl.py#L203C3-L203C3

Referring to links, I think INPUT.IMAGE_SIZE need to be changed.  So currently the image can be resized only to image_height=image_width=INPUT.IMAGE_SIZE  ? Different dimensions not supported?

**Comment by FengLi-ust** [comment]
Sorry for the late reply. This is only the training setting, we use 1024x1024 image size. The inference image size can be arbitrary.
