### ISSUE TITLE
Reproduction results with 12 epochs on COCO

### ISSUE THREAD

**Issue by xianghong2023** [IDEA-Research/MaskDINO#99]
Dear Author, I trained directly on the configs/coco/instance-segmentation/maskdino_R50_bs16_50ep_3s_dowsample1_2048.yaml configuration using 4xa100 GPUs and got the following results, which are quite different from the performance you reported . I just modified the training configuration STEPS:(55000, ) and MAX_ITER: 60000. can you provide the detailed training configuration file?
> 
> [12/02 02:09:10] d2.engine.defaults INFO: Evaluation results for coco_2017_val in csv format:
> [12/02 02:09:10] d2.evaluation.testing INFO: copypaste: Task: bbox
> [12/02 02:09:10] d2.evaluation.testing INFO: copypaste: AP,AP50,AP75,APs,APm,APl
> [12/02 02:09:10] d2.evaluation.testing INFO: copypaste: 43.3909,62.0632,47.0170,24.8990,46.6183,59.0534
> [12/02 02:09:10] d2.evaluation.testing INFO: copypaste: Task: segm
> [12/02 02:09:10] d2.evaluation.testing INFO: copypaste: AP,AP50,AP75,APs,APm,APl
> [12/02 02:09:10] d2.evaluation.testing INFO: copypaste: 39.7679,60.6735,42.8796,19.4318,42.5826,59.4144

The repo is bbox map 45.7 mask map 41.4 but I got bbox map 43.4 mask map 39.8.
This question has been bothering me for a long time and I really hope to receive your answer.

**Comment by Linwei-Chen** [comment]
> Dear Author, I trained directly on the configs/coco/instance-segmentation/maskdino_R50_bs16_50ep_3s_dowsample1_2048.yaml configuration using 4xa100 GPUs and got the following results, which are quite different from the performance you reported . I just modified the training configuration STEPS:(55000, ) and MAX_ITER: 60000. can you provide the detailed training configuration file?
> 
> > [12/02 02:09:10] d2.engine.defaults INFO: Evaluation results for coco_2017_val in csv format:
> > [12/02 02:09:10] d2.evaluation.testing INFO: copypaste: Task: bbox
> > [12/02 02:09:10] d2.evaluation.testing INFO: copypaste: AP,AP50,AP75,APs,APm,APl
> > [12/02 02:09:10] d2.evaluation.testing INFO: copypaste: 43.3909,62.0632,47.0170,24.8990,46.6183,59.0534
> > [12/02 02:09:10] d2.evaluation.testing INFO: copypaste: Task: segm
> > [12/02 02:09:10] d2.evaluation.testing INFO: copypaste: AP,AP50,AP75,APs,APm,APl
> > [12/02 02:09:10] d2.evaluation.testing INFO: copypaste: 39.7679,60.6735,42.8796,19.4318,42.5826,59.4144
> 
> The repo is bbox map 45.7 mask map 41.4 but I got bbox map 43.4 mask map 39.8. This question has been bothering me for a long time and I really hope to receive your answer.

Hello~, can you share your training log.txt of 12 epoch, it can be helpful, thanks a lot!

**Comment by xianghong2023** [comment]
You can try to set MAX_ITER: 88500 and STEPS: (81125, ). In MaskDINO, one epoch should be 7375 steps.



---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 日期 | 2025年02月26日 19:27 |
| 收件人 | ***@***.***> |
| 抄送至 | ***@***.***>、State ***@***.***> |
| 主题 | Re: [IDEA-Research/MaskDINO] Reproduction results with 12 epochs on COCO (Issue #99) |

Dear Author, I trained directly on the configs/coco/instance-segmentation/maskdino_R50_bs16_50ep_3s_dowsample1_2048.yaml configuration using 4xa100 GPUs and got the following results, which are quite different from the performance you reported . I just modified the training configuration STEPS:(55000, ) and MAX_ITER: 60000. can you provide the detailed training configuration file?

[12/02 02:09:10] d2.engine.defaults INFO: Evaluation results for coco_2017_val in csv format:
[12/02 02:09:10] d2.evaluation.testing INFO: copypaste: Task: bbox
[12/02 02:09:10] d2.evaluation.testing INFO: copypaste: AP,AP50,AP75,APs,APm,APl
[12/02 02:09:10] d2.evaluation.testing INFO: copypaste: 43.3909,62.0632,47.0170,24.8990,46.6183,59.0534
[12/02 02:09:10] d2.evaluation.testing INFO: copypaste: Task: segm
[12/02 02:09:10] d2.evaluation.testing INFO: copypaste: AP,AP50,AP75,APs,APm,APl
[12/02 02:09:10] d2.evaluation.testing INFO: copypaste: 39.7679,60.6735,42.8796,19.4318,42.5826,59.4144

The repo is bbox map 45.7 mask map 41.4 but I got bbox map 43.4 mask map 39.8. This question has been bothering me for a long time and I really hope to receive your answer.

Hello~, can you share your training log.txt of 12 epoch, it can be helpful, thanks a lot!

—
Reply to this email directly, view it on GitHub, or unsubscribe.
You are receiving this because you modified the open/close state.Message ID: ***@***.***>

Linwei-Chen left a comment (IDEA-Research/MaskDINO#99)

Dear Author, I trained directly on the configs/coco/instance-segmentation/maskdino_R50_bs16_50ep_3s_dowsample1_2048.yaml configuration using 4xa100 GPUs and got the following results, which are quite different from the performance you reported . I just modified the training configuration STEPS:(55000, ) and MAX_ITER: 60000. can you provide the detailed training configuration file?

[12/02 02:09:10] d2.engine.defaults INFO: Evaluation results for coco_2017_val in csv format:
[12/02 02:09:10] d2.evaluation.testing INFO: copypaste: Task: bbox
[12/02 02:09:10] d2.evaluation.testing INFO: copypaste: AP,AP50,AP75,APs,APm,APl
[12/02 02:09:10] d2.evaluation.testing INFO: copypaste: 43.3909,62.0632,47.0170,24.8990,46.6183,59.0534
[12/02 02:09:10] d2.evaluation.testing INFO: copypaste: Task: segm
[12/02 02:09:10] d2.evaluation.testing INFO: copypaste: AP,AP50,AP75,APs,APm,APl
[12/02 02:09:10] d2.evaluation.testing INFO: copypaste: 39.7679,60.6735,42.8796,19.4318,42.5826,59.4144

The repo is bbox map 45.7 mask map 41.4 but I got bbox map 43.4 mask map 39.8. This question has been bothering me for a long time and I really hope to receive your answer.

Hello~, can you share your training log.txt of 12 epoch, it can be helpful, thanks a lot!

**Comment by Linwei-Chen** [comment]
> You can try to set MAX_ITER: 88500 and STEPS: (81125, ). In MaskDINO, one epoch should be 7375 steps.
> […](#)
> 
> ---- 回复的原邮件 ----
> | 发件人 | ***@***.***> |
> | 日期 | 2025年02月26日 19:27 |
> | 收件人 | ***@***.***> |
> | 抄送至 | ***@***.***>、State ***@***.***> |
> | 主题 | Re: [IDEA-Research/MaskDINO] Reproduction results with 12 epochs on COCO (Issue [#99](https://github.com/IDEA-Research/MaskDINO/issues/99)) |
> 
> Dear Author, I trained directly on the configs/coco/instance-segmentation/maskdino_R50_bs16_50ep_3s_dowsample1_2048.yaml configuration using 4xa100 GPUs and got the following results, which are quite different from the performance you reported . I just modified the training configuration STEPS:(55000, ) and MAX_ITER: 60000. can you provide the detailed training configuration file?
> 
> [12/02 02:09:10] d2.engine.defaults INFO: Evaluation results for coco_2017_val in csv format:
> [12/02 02:09:10] d2.evaluation.testing INFO: copypaste: Task: bbox
> [12/02 02:09:10] d2.evaluation.testing INFO: copypaste: AP,AP50,AP75,APs,APm,APl
> [12/02 02:09:10] d2.evaluation.testing INFO: copypaste: 43.3909,62.0632,47.0170,24.8990,46.6183,59.0534
> [12/02 02:09:10] d2.evaluation.testing INFO: copypaste: Task: segm
> [12/02 02:09:10] d2.evaluation.testing INFO: copypaste: AP,AP50,AP75,APs,APm,APl
> [12/02 02:09:10] d2.evaluation.testing INFO: copypaste: 39.7679,60.6735,42.8796,19.4318,42.5826,59.4144
> 
> The repo is bbox map 45.7 mask map 41.4 but I got bbox map 43.4 mask map 39.8. This question has been bothering me for a long time and I really hope to receive your answer.
> 
> Hello~, can you share your training log.txt of 12 epoch, it can be helpful, thanks a lot!
> 
> —
> Reply to this email directly, view it on GitHub, or unsubscribe.
> You are receiving this because you modified the open/close state.Message ID: ***@***.***>
> 
> Linwei-Chen left a comment ([IDEA-Research/MaskDINO#99](https://github.com/IDEA-Research/MaskDINO/issues/99))
> 
> Dear Author, I trained directly on the configs/coco/instance-segmentation/maskdino_R50_bs16_50ep_3s_dowsample1_2048.yaml configuration using 4xa100 GPUs and got the following results, which are quite different from the performance you reported . I just modified the training configuration STEPS:(55000, ) and MAX_ITER: 60000. can you provide the detailed training configuration file?
> 
> [12/02 02:09:10] d2.engine.defaults INFO: Evaluation results for coco_2017_val in csv format:
> [12/02 02:09:10] d2.evaluation.testing INFO: copypaste: Task: bbox
> [12/02 02:09:10] d2.evaluation.testing INFO: copypaste: AP,AP50,AP75,APs,APm,APl
> [12/02 02:09:10] d2.evaluation.testing INFO: copypaste: 43.3909,62.0632,47.0170,24.8990,46.6183,59.0534
> [12/02 02:09:10] d2.evaluation.testing INFO: copypaste: Task: segm
> [12/02 02:09:10] d2.evaluation.testing INFO: copypaste: AP,AP50,AP75,APs,APm,APl
> [12/02 02:09:10] d2.evaluation.testing INFO: copypaste: 39.7679,60.6735,42.8796,19.4318,42.5826,59.4144
> 
> The repo is bbox map 45.7 mask map 41.4 but I got bbox map 43.4 mask map 39.8. This question has been bothering me for a long time and I really hope to receive your answer.
> 
> Hello~, can you share your training log.txt of 12 epoch, it can be helpful, thanks a lot!
> 
> —
> Reply to this email directly, view it on GitHub, or unsubscribe.
> You are receiving this because you modified the open/close state.Message ID: ***@***.***>

Thank you very much! I’m wondering how the AP improves with each epoch to check if I’ve done everything correctly. I’ve just finished training the second epoch and got a box AP of 32.0. If you could share your full training log.txt for the 12 epochs, it would be very helpful. Thank you so much!
